### GENERAL ###
server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

logging:
  level:
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: '*'

springdoc:
  swagger-ui:
    path: /swagger-ui.html

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/RNFRoboEmissorNf?zeroDateTimeBehavior=convertToNull
  jpa:
    show-sql: true
    properties:
      hibernate:
         dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false

onesignal:
  url: https://onesignal.com/api/v1
  app-id: 1312743e-26a8-47b1-800f-b8c074e5ceab
  rest-key: NjdhNWRkMzQtYTIxMi00ZTJiLWJjMjctM2ViZDgxNjc
  app-id-return: 5e81832e-d05e-42c7-b217-58bd40
  onesignal.rest-key-return: NGU5MTE3MGUtNTE2OS00ZDQ4LTkyMTYtZWRkM

amazon:
  accessKey:
  secretKey:
